export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_INPUTVALUE = 'CHANGE_INPUTVALUE'
export const HANDLE_BTN_CLICK = 'HANDLE_BTN_CLICK'
export const HANDLE_CLICK_DELETE = 'HANDLE_CLICK_DELETE'